# Generated by Django 2.1.5 on 2020-04-05 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompliantCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('completion_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('class_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'In Progress'), ('3', 'Done'), ('4', 'Cancelled')], default='1', max_length=20)),
                ('class_description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(verbose_name='EMPLOYEE ID')),
                ('surname', models.CharField(max_length=255, verbose_name='SURNAME')),
                ('given_name', models.CharField(max_length=255, verbose_name='GIVEN NAME')),
                ('email_add', models.CharField(max_length=255, verbose_name='EMAIL ADDRESS')),
                ('status', models.BooleanField(blank=True, default=True, verbose_name='STATUS')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='manager_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Manager', verbose_name='MANAGER'),
        ),
        migrations.AddField(
            model_name='employee',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Section', verbose_name='SECTION'),
        ),
        migrations.AddField(
            model_name='compliantcourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='compliantcourse',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Employee', verbose_name='Employee'),
        ),
    ]
