# Generated by Django 2.1.5 on 2020-04-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200405_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliantcourse',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='compliantcourse',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='compliantcourse',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Employee', verbose_name='Employee'),
        ),
    ]
