# Generated by Django 2.1.5 on 2020-04-05 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200405_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliantcourse',
            name='section',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
