# Generated by Django 2.1.5 on 2020-04-08 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_compliantcourse_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliantcourse',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Section', verbose_name='SECTION'),
        ),
    ]
